In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('E:/ANUBHAV/VS Code/ML/Datasets/Data/DS 92/train.csv')
data

fLength   fWidth   fSize   fConc  fConc1     fAsym  fM3Long  fM3Trans  \
0      20.1426   9.9778  2.2695  0.6022  0.3898   -4.7403  15.5312   -9.5154   
1      19.8300   7.3303  2.2541  0.7521  0.4095    2.8528  -9.7666    5.0346   
2     163.3320  13.8819  2.9395  0.2540  0.1293 -131.0740 -75.0854   -8.5308   
3      13.2942  10.6649  2.1804  0.7855  0.3927  -15.0000  -0.3975   11.9048   
4      85.2934  38.3607  3.8050  0.1791  0.0972   -5.1982  72.7592   23.6211   
...        ...      ...     ...     ...     ...       ...      ...       ...   
4995   48.6388   9.0466  2.5849  0.4343  0.2432    6.8177  45.4794   -7.6617   
4996   77.0229  25.0324  3.2476  0.2482  0.1496  -60.2780  51.9473  -14.5936   
4997   71.3527  17.8546  3.0853  0.1749  0.0932  142.7684 -20.1101   -3.5355   
4998   33.0857  19.4052  2.6264  0.4087  0.2226  -10.6070 -14.8030  -13.1350   
4999   30.1651  16.4522  2.8901  0.3335  0.2041    2.6149  13.3085   10.4100   

       fAlpha     fDist class  
0     17.6460   56.5999     g  
1     13.7940  108.4640     g  
2     58.8365  118.2360     h  
3     67.6577  118.3830     g  
4      3.1040  354.7870     g  
...       ...       ...   ...  
4995   0.2040  188.9570     g  
4996   4.1493  270.5950     g  
4997  16.6362  155.5068     h  
4998  19.2177  256.7284     h  
4999   7.4430  168.6760     g  

[5000 rows x 11 columns]

In [3]:
x = np.array(data.drop(['class'], axis=1))
y = np.array(data['class'])
x, y

(array([[ 20.1426,   9.9778,   2.2695, ...,  -9.5154,  17.646 ,  56.5999],
        [ 19.83  ,   7.3303,   2.2541, ...,   5.0346,  13.794 , 108.464 ],
        [163.332 ,  13.8819,   2.9395, ...,  -8.5308,  58.8365, 118.236 ],
        ...,
        [ 71.3527,  17.8546,   3.0853, ...,  -3.5355,  16.6362, 155.5068],
        [ 33.0857,  19.4052,   2.6264, ..., -13.135 ,  19.2177, 256.7284],
        [ 30.1651,  16.4522,   2.8901, ...,  10.41  ,   7.443 , 168.676 ]]),
 array(['g', 'g', 'h', ..., 'h', 'h', 'g'], dtype=object))

In [4]:
from sklearn.preprocessing import StandardScaler

In [5]:
scale = StandardScaler()
x = scale.fit_transform(x)
x

array([[-0.76676058, -0.6637131 , -1.16324595, ..., -0.47976998,
        -0.39116243, -1.85362899],
       [-0.77405657, -0.80921526, -1.19578971, ...,  0.23112446,
        -0.53822945, -1.1490465 ],
       [ 2.57523716, -0.4491503 ,  0.2526186 , ..., -0.43166368,
         1.18146579, -1.01629224],
       ...,
       [ 0.42846783, -0.23081737,  0.56072763, ..., -0.1875997 ,
        -0.42971598, -0.50996218],
       [-0.4646725 , -0.14559899, -0.40903393, ..., -0.65661902,
        -0.33115588,  0.86515021],
       [-0.53283843, -0.30789092,  0.148225  , ...,  0.49375964,
        -0.78070676, -0.33105639]])

In [6]:
from collections import Counter

In [7]:
Counter(y)

Counter({'g': 3222, 'h': 1778})

In [8]:
for i in range(len(y)):
    if y[i] == 'g':
        y[i] = 0
    else:
        y[i] = 1
y

array([0, 0, 1, ..., 1, 1, 0], dtype=object)

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
y = y.astype('int')
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.2)

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import *

In [12]:
lr = LogisticRegression()
lr.fit(train_x, train_y)
ans = lr.predict(test_x)
print(accuracy_score(ans, test_y))
print(confusion_matrix(ans, test_y))

0.789
[[574 162]
 [ 49 215]]


In [13]:
lr = DecisionTreeClassifier()
lr.fit(train_x, train_y)
ans = lr.predict(test_x)
print(accuracy_score(ans, test_y))
print(confusion_matrix(ans, test_y))

0.8
[[531 108]
 [ 92 269]]


In [14]:
lr = RandomForestClassifier(n_estimators=250, criterion='entropy')
lr.fit(train_x, train_y)
ans = lr.predict(test_x)
print(accuracy_score(ans, test_y))
print(confusion_matrix(ans, test_y))

0.856
[[588 109]
 [ 35 268]]


In [15]:
from sklearn.model_selection import cross_val_score

lr = RandomForestClassifier()
acc = cross_val_score(lr, x, y, cv=5)
acc.mean()

0.8654

Genetic Algorithms

In [ ]:
from tpot import TPOTClassifier

In [ ]:
params = {'n_estimators': np.arange(100, 1300, 100), 'criterion': ['gini', 'entropy'], 'max_features':
         ['auto', 'sqrt', 'log2'], 'max_depth': np.arange(10, 480, 30), 'min_samples_split': np.arange(2, 22, 2)}

params

In [ ]:
clf = TPOTClassifier(generations=5, population_size=24, offspring_size=12, verbosity=2, early_stop=12,
                     config_dict={'sklearn.ensemble.RandomForestClassifier': params}, cv=5, scoring='accuracy')

clf.fit(train_x, train_y)

In [ ]:
clf.score(test_x, test_y)

Using Optuna

In [16]:
import optuna as op

c:\Users\anubh\anaconda3\envs\tf_gpu\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [20]:
def objective(trial):
    n = trial.suggest_int('n_estimators', 50, 500, step=50)
    algo = trial.suggest_categorical('criterion', ['gini', 'entropy'])
    max_f = trial.suggest_categorical('max_features', ['auto', 'sqrt', 'log2'])
    max_d = trial.suggest_int('max_depth', 10, 510, step=30)
    msp = trial.suggest_int('min_samples_split', 2, 22, step=2)
    m = RandomForestClassifier(n_estimators=n, criterion=algo, max_features=max_f, max_depth=max_d, min_samples_split=msp)
    return cross_val_score(m, x, y, cv=5).mean()

In [21]:
opt = op.create_study()
opt.optimize(objective, n_trials=10)

[I 2022-10-13 17:15:47,637] A new study created in memory with name: no-name-359c49d3-e4fd-4650-9eb0-a4e72589c24f
c:\Users\anubh\anaconda3\envs\tf_gpu\lib\site-packages\optuna\distributions.py:683: UserWarning: The distribution is specified by [10, 510] and step=30, but the range is not divisible by `step`. It will be replaced by [10, 490].
  warnings.warn(
[I 2022-10-13 17:15:53,029] Trial 0 finished with value: 0.8648 and parameters: {'n_estimators': 100, 'criterion': 'entropy', 'max_features': 'sqrt', 'max_depth': 130, 'min_samples_split': 16}. Best is trial 0 with value: 0.8648.
c:\Users\anubh\anaconda3\envs\tf_gpu\lib\site-packages\optuna\distributions.py:683: UserWarning: The distribution is specified by [10, 510] and step=30, but the range is not divisible by `step`. It will be replaced by [10, 490].
  warnings.warn(
[I 2022-10-13 17:16:10,036] Trial 1 finished with value: 0.8632 and parameters: {'n_estimators': 350, 'criterion': 'entropy', 'max_features': 'sqrt', 'max_depth': 2

In [22]:
opt.best_params, opt.best_value

({'n_estimators': 50,
  'criterion': 'gini',
  'max_features': 'auto',
  'max_depth': 10,
  'min_samples_split': 16},
 0.8583999999999999)